/* tslint:disable */
/* eslint-disable */
/**
 * TypeScript declaration file for funding-viz WASM module
 * This file is auto-generated by wasm-pack during build
 * Placeholder declarations for development
 */

export function init(): void;
export function version(): string;
export function benchmark_canvas(canvas_id: string, iterations: number): number;
export function create_default_theme(): any;
export function render_simple_progress(
  canvas_id: string,
  value: number,
  max_value: number,
  label: string,
  color: string
): void;

export class ScoreDistributionChart {
  constructor(canvas_id: string, config: any);
  set_data(data: any, bin_count: number): void;
  render(): void;
  on_mouse_move(x: number, y: number): any;
  get_stats(): any;
  free(): void;
}

export class ProgressTrackerChart {
  constructor(canvas_id: string, config: any);
  set_data(data: any): void;
  set_center_label(label: string): void;
  render(): void;
  animate(delta_ms: number): boolean;
  on_mouse_move(x: number, y: number): any;
  get_stats(): any;
  free(): void;
}

export class VarianceHeatmapChart {
  constructor(canvas_id: string, config: any);
  set_variance_threshold(threshold: number): void;
  set_data(data: any): void;
  render(): void;
  on_scroll(delta_y: number): void;
  on_mouse_move(x: number, y: number): any;
  get_flagged(): any;
  get_stats(): any;
  free(): void;
}

export class TimelineChart {
  constructor(canvas_id: string, config: any);
  set_show_cumulative(show: boolean): void;
  set_data(data: any): void;
  set_events(events: any): void;
  set_granularity(granularity: string): void;
  render(): void;
  on_mouse_move(x: number, y: number): any;
  get_stats(): any;
  free(): void;
}

export class NetworkGraphChart {
  constructor(canvas_id: string, config: any);
  set_data(nodes: any, edges: any): void;
  set_physics(repulsion: number, attraction: number, damping: number): void;
  toggle_simulation(): boolean;
  step_simulation(): boolean;
  render(): void;
  on_zoom(delta: number, center_x: number, center_y: number): void;
  on_pan(dx: number, dy: number): void;
  on_mouse_down(x: number, y: number): boolean;
  on_mouse_up(): void;
  on_mouse_move(x: number, y: number): any;
  on_click(x: number, y: number, multi_select: boolean): any;
  get_stats(): any;
  reset_view(): void;
  fit_to_content(): void;
  free(): void;
}
