/**
 * Placeholder JavaScript for funding-viz WASM module
 * This file is auto-generated by wasm-pack during build
 *
 * In development, this placeholder provides mock implementations
 * In production, wasm-pack generates the actual bindings
 */

let wasm;

const cachedTextDecoder = (typeof TextDecoder !== 'undefined' ? new TextDecoder('utf-8', { ignoreBOM: true, fatal: true }) : { decode: () => { throw Error('TextDecoder not available'); } });

let cachedUint8Memory0 = null;

function getUint8Memory0() {
  if (cachedUint8Memory0 === null || cachedUint8Memory0.byteLength === 0) {
    cachedUint8Memory0 = new Uint8Array(wasm.memory.buffer);
  }
  return cachedUint8Memory0;
}

function getStringFromWasm0(ptr, len) {
  ptr = ptr >>> 0;
  return cachedTextDecoder.decode(getUint8Memory0().subarray(ptr, ptr + len));
}

export function init() {
  console.warn('[WASM] Using placeholder module. Build with wasm-pack for production.');
}

export function version() {
  return '0.1.0-placeholder';
}

export function benchmark_canvas(canvas_id, iterations) {
  console.warn('[WASM] benchmark_canvas: placeholder');
  return 0;
}

export function create_default_theme() {
  return {
    primary: '#3B82F6',
    secondary: '#6B7280',
    success: '#10B981',
    warning: '#F59E0B',
    danger: '#EF4444',
    background: '#FFFFFF',
    text: '#1F2937',
    grid: '#E5E7EB',
    accent: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#EC4899', '#06B6D4', '#84CC16'],
  };
}

export function render_simple_progress(canvas_id, value, max_value, label, color) {
  console.warn('[WASM] render_simple_progress: placeholder');
  // Basic canvas fallback
  const canvas = document.getElementById(canvas_id);
  if (canvas) {
    const ctx = canvas.getContext('2d');
    const width = canvas.width;
    const height = canvas.height;
    const centerX = width / 2;
    const centerY = height / 2;
    const radius = Math.min(width, height) / 2 - 20;

    ctx.clearRect(0, 0, width, height);

    // Background circle
    ctx.beginPath();
    ctx.arc(centerX, centerY, radius, 0, Math.PI * 2);
    ctx.strokeStyle = '#E5E7EB';
    ctx.lineWidth = radius * 0.15;
    ctx.stroke();

    // Progress arc
    const progress = value / max_value;
    ctx.beginPath();
    ctx.arc(centerX, centerY, radius, -Math.PI / 2, -Math.PI / 2 + progress * Math.PI * 2);
    ctx.strokeStyle = color;
    ctx.stroke();

    // Text
    ctx.fillStyle = '#1F2937';
    ctx.font = `bold ${radius * 0.4}px Inter, system-ui, sans-serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(`${Math.round(progress * 100)}%`, centerX, centerY - 5);

    ctx.font = `${radius * 0.2}px Inter, system-ui, sans-serif`;
    ctx.fillStyle = '#6B7280';
    ctx.fillText(label, centerX, centerY + radius * 0.3);
  }
}

// Placeholder classes
class PlaceholderChart {
  constructor(canvasId, config) {
    this.canvasId = canvasId;
    this.config = config;
    console.warn(`[WASM] ${this.constructor.name}: Using placeholder. Build with wasm-pack for full functionality.`);
  }

  render() {
    const canvas = document.getElementById(this.canvasId);
    if (canvas) {
      const ctx = canvas.getContext('2d');
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.fillStyle = '#F3F4F6';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.fillStyle = '#6B7280';
      ctx.font = '14px Inter, system-ui, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('Build WASM module for visualization', canvas.width / 2, canvas.height / 2 - 10);
      ctx.fillText('Run: cd wasm-viz && ./build.sh', canvas.width / 2, canvas.height / 2 + 10);
    }
  }

  free() {}
}

export class ScoreDistributionChart extends PlaceholderChart {
  set_data(data, bin_count) {}
  on_mouse_move(x, y) { return { hit: false }; }
  get_stats() { return { totalApplications: 0, binCount: 0 }; }
}

export class ProgressTrackerChart extends PlaceholderChart {
  set_data(data) {}
  set_center_label(label) {}
  animate(delta_ms) { return false; }
  on_mouse_move(x, y) { return { hit: false }; }
  get_stats() { return { totalCompleted: 0, totalItems: 0 }; }
}

export class VarianceHeatmapChart extends PlaceholderChart {
  set_variance_threshold(threshold) {}
  set_data(data) {}
  on_scroll(delta_y) {}
  on_mouse_move(x, y) { return { hit: false }; }
  get_flagged() { return []; }
  get_stats() { return { totalApplications: 0, flaggedCount: 0 }; }
}

export class TimelineChart extends PlaceholderChart {
  set_show_cumulative(show) {}
  set_data(data) {}
  set_events(events) {}
  set_granularity(granularity) {}
  on_mouse_move(x, y) { return { hit: false }; }
  get_stats() { return { totalSubmissions: 0, peakCount: 0 }; }
}

export class NetworkGraphChart extends PlaceholderChart {
  set_data(nodes, edges) {}
  set_physics(repulsion, attraction, damping) {}
  toggle_simulation() { return false; }
  step_simulation() { return false; }
  on_zoom(delta, center_x, center_y) {}
  on_pan(dx, dy) {}
  on_mouse_down(x, y) { return false; }
  on_mouse_up() {}
  on_mouse_move(x, y) { return { hit: false }; }
  on_click(x, y, multi_select) { return { selected: [] }; }
  get_stats() { return { nodeCount: 0, edgeCount: 0 }; }
  reset_view() {}
  fit_to_content() {}
}

export default init;
